version: "2.0"

services:
  dev_pyprometheustest_flask_app:
    image: dev_pyprometheus_flask_app:latest
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - "rm -rf /usr/src/app/storage/prometheus/* && uwsgi --ini=/usr/src/app/uwsgi.ini"
    volumes:
      - ./uwsgi.ini:/usr/src/app/uwsgi.ini
      - ./:/usr/src/app/

    ports:
      - 8051:8051

    networks:
      - default

networks:
  default: